### ISSUE TITLE
Fresh build from source expects config.toml

### ISSUE THREAD

**Issue by Aflynn50** [PietroPasotti/jhack#38] opened 2023-01-13 17:21 UTC
A fresh install with `git clone`, `pip install -r requirements` then `python3 main.py` gives an error that the config file cannot be found

```python
Traceback (most recent call last):
  File "/home/aflynn50/Canonical/jhack/jhack/main.py", line 43, in <module>
    from jhack.utils.nuke import nuke
  File "/home/aflynn50/Canonical/jhack/jhack/utils/nuke.py", line 22, in <module>
    ASK_FOR_CONFIRMATION = CONFIG["nuke"]["ask_for_confirmation"]
  File "/home/aflynn50/Canonical/jhack/jhack/conf/conf.py", line 32, in __getitem__
    return self.data[item]
  File "/home/aflynn50/Canonical/jhack/jhack/conf/conf.py", line 25, in data
    self._load()
  File "/home/aflynn50/Canonical/jhack/jhack/conf/conf.py", line 20, in _load
    self._data = toml.load(self._path.open())
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/aflynn50/.jhack_config.toml'
```
When this file is created then we get another error

```python
Traceback (most recent call last):
  File "/home/aflynn50/Canonical/jhack/jhack/main.py", line 43, in <module>
    from jhack.utils.nuke import nuke
  File "/home/aflynn50/Canonical/jhack/jhack/utils/nuke.py", line 22, in <module>
    ASK_FOR_CONFIRMATION = CONFIG["nuke"]["ask_for_confirmation"]
  File "/home/aflynn50/Canonical/jhack/jhack/conf/conf.py", line 32, in __getitem__
    return self.data[item]
KeyError: 'nuke'
```
Which can apparently be fixed by putting `echo "nuke.ask_for_confirmation = false" > ~/.jhack/config.toml`

**Comment by hypeitnow** [comment] 2023-01-14 17:21
Things get funny when you installed this snap as root  :D 

root@juju-client:~# jhack replay list mysql-innodb-cluster/1
Traceback (most recent call last):
  File "/snap/jhack/149/bin/jhack", line 5, in <module>
    from jhack.main import main
  File "/snap/jhack/149/lib/python3.8/site-packages/jhack/main.py", line 43, in <module>
    from jhack.utils.nuke import nuke
  File "/snap/jhack/149/lib/python3.8/site-packages/jhack/utils/nuke.py", line 22, in <module>
    ASK_FOR_CONFIRMATION = CONFIG["nuke"]["ask_for_confirmation"]
  File "/snap/jhack/149/lib/python3.8/site-packages/jhack/conf/conf.py", line 32, in __getitem__
    return self.data[item]
  File "/snap/jhack/149/lib/python3.8/site-packages/jhack/conf/conf.py", line 25, in data
    self._load()
  File "/snap/jhack/149/lib/python3.8/site-packages/jhack/conf/conf.py", line 20, in _load
    self._data = toml.load(self._path.open())
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/root/.jhack_config.toml'
root@juju-client:~#

**Comment by PietroPasotti** [comment] 2023-01-17 09:11
Thanks for the report, folks! It should be fixed now for local installs, and the edge snap is indeed broken. Please use more stable versions for the time being, they should be still working.
The issue is that the home-read interface the snap was using does not apply to hidden directories, so I had to request a new interface for that, which however requires manual approval, which is pending.
Hopefully I'll get it soon :)

**Closed by PietroPasotti** 2023-01-17 09:11 UTC

**Comment by PietroPasotti** [comment] 2023-01-17 09:55
---> https://forum.snapcraft.io/t/please-allow-personal-files-interface-for-jhack/33517
